config/routes.rb
Rails.application.routes.draw do
  # get 'questions/ask'
  # get 'questions/answer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'ask', to: 'questions#ask', as: :ask
  get 'answer', to: 'questions#answer', as: :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @question = params[:question]
    if @question.downcase == "i am going to work right now!"
      @answer = "Great!"
    elsif @question[-1] != "?"
      @answer = "I don't care, get dressed and go to work!"
    elsif @question[-1] == "?"
      @answer = "Silly question, get dressed and go to work!"
    end
  end
end



# def coach_answer(your_message)
#   # TODO: return coach answer to your_message
#   if your_message == "I am going to work right now!"
#     return ""
#   elsif your_message[-1] != "?"
#     return "I don't care, get dressed and go to work!"
#   elsif your_message[-1] == "?"
#     return "Silly question, get dressed and go to work!"
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsStupidCoaching</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class= "container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/questions/answer.html.erb
<h1>Stupid coach</h1>

<p><%= @answer %></p>
<p><%= link_to "Ask another question", ask_path, :class => "badge badge-warning" %></p>

app/views/questions/ask.html.erb
<div class="mx-sm-3 mb-2">
  <h1>Stupid coach</h1>
</div>


<form action="/answer" method="get" class="form-inline">
  <div class="form-group mx-sm-3 mb-2">
    <input type="text" name="question" placeholder="Ask your coach anything" class="form-control">
  </div>
  <button type="submit" class="btn btn-primary mb-2">Ask</button>
</form>